export default [
    {
        id: 1,
        category: 'Team',
        img: "../assets/neil-resized.png",
        alt: "Neil Zumwalde",
        name: "Neil Zumwalde",
        title: "Vision & Product",
        description: "An Electrical/Software Engineer, Neil has developed products and provided technical advisement in blockchain, industrial automation, and renewable energy markets. To Neil, nothing is impossible.",
        descriptiontwo: "In his spare time he writes music for children and podcasts.",
        twitter: "https://twitter.com/neilzum",
        linkedin: "https://www.linkedin.com/in/neilzumwalde/",
    },
    {
        id: 2,
        category: 'Team',
        img: "../assets/momin.jpg",
        alt: "Momin Ahmad ",
        name: "Momin Ahmad",
        title: "Marketing",
        description: "Momin is Credmark’s secret weapon. He is versatile, a quick study, and usually in a good mood after 10AM. Besides being responsible for the development of Credmark’s projects, Momin is the author of our Crypto Credit Report.",
        descriptiontwo: "Outside of work, he enjoys playing bluegrass on his upright bass.",
        twitter: "https://twitter.com/mostarz93",
        linkedin: "https://www.linkedin.com/in/momin-ahmad/",
    },
    {
        id: 3,
        category: 'Team',
        img: "../assets/paul.jpg",
        alt: "Paul Murphy",
        name: "Paul Murphy",
        title: "Operations",
        description: "Born in Argentina, Paul has lived and worked all over the world. He used to write a lot of code. Now he’s kind of rusty. He does whatever needs doing, whether or not it’s fun.",
        descriptiontwo: "He believes the answer to most questions can be found in musical and opera scores.",
        twitter: "https://twitter.com/prmurphy",
        linkedin: "https://www.linkedin.com/in/prmurphy/",
    },
    {
        id: 5,
        category: 'Team',
        img: "../assets/matt.png",
        alt: "Matthias Knauth",
        name: "Matthias Knauth",
        title: "Product",
        twitter: "https://twitter.com/MatthiasKnauth",
        linkedin: "https://www.linkedin.com/in/matthias-knauth-b96b6b37/",
    },
    {
        id: 6,
        category: 'Team',
        img: "../assets/Asan.png",
        alt: "Asan Tulemis",
        name: "Asan Tulemis",
        title: "Risk",
        description: "Asan has worked in the risk departments of two of Australia’s largest banks. He has a PhD in applied math. He loves risk strategy and building the most complicated risk models.",
        twitter: "https://twitter.com/atulemis1",
        linkedin: "https://www.linkedin.com/in/atulemis/",
    },
    {
        id: 7,
        category: 'Team',
        img: "../assets/nisch.jpg",
        alt: "Nishchal Gaba",
        name: "Nishchal Gaba",
        title: "Data Science",
        description: "Nish eats data instead of food. Armed with a Master’s in AI from Edinburgh University, he has become one of India’s greatest technologists.",
        descriptiontwo: "Outside of work he writes and reviews academic papers. For fun.",
        twitter: "https://twitter.com/gaba_nishchal",
        linkedin: "https://www.linkedin.com/in/nishchal-gaba-295701a5/",
    },
    {
        id: 8,
        category: 'Team',
        img: "../assets/collier.jpg",
        alt: "Collier Gray",
        name: "Collier Gray",
        title: "Operations",
        description: "A native Austinite, Collier spent 6 years in technology and finance in NYC, working from Product to leading a Lean Governance group.",
        descriptiontwo: "When he's not working through his substantial to-do list, you can find Collier reading and trying to keep his vegetable garden alive.",
        twitter: "https://twitter.com/JoeCollierGray",
        linkedin: "https://www.linkedin.com/in/joseph-collier-gray-7a323054/",
    },
    {
        id: 9,
        category: 'Team',
        img: "../assets/stijn.jpg",
        alt: "Stijn Dobbelaere",
        name: "Stijn Dobbelaere",
        title: "Design",
        description: "From editing national ad campaigns for Capital One, to creating viral-ready memes for Southwest Airlines, to voicing Pizza Hut commercials, Stijn has  years of experience in design, advertising and marketing.",
        descriptiontwo: "Outside of his work, he bangs loudly on drums.",
        twitter: "https://twitter.com/S7IJN",
        linkedin: "https://www.linkedin.com/in/stijn-dobbelaere-5b9a476b/",
    },
    {
        id: 10,
        category: 'Team',
        img: "../assets/when.png",
        alt: "Wen-Chiao",
        name: "Wen-Chiao",
        title: "Community",
        description: "Originally from Taiwan,  Wen-Chiao grew up in the US, went back to Taiwan for high school, and then moved to Japan for university. He’s worked in both Taipei and Tokyo in tech and innovation. In his spare time, he likes reading and asking questions.",
        twitter: "https://twitter.com/wc_su95",
        linkedin: "https://www.linkedin.com/in/wen-chiao-su/",
    },
    {
        id: 11,
        category: 'Team',
        img: "../assets/joey.jpg",
        alt: "Joseph Hirsh",
        name: "Joseph Hirsh",
        title: "Data",
        description: "After receiving a PhD in algebraic topology and postdoctoral fellowships at MIT and MSRI, Joe worked in blockchain/AI consulting and served as a mentor for dLab.",
        descriptiontwo: "Outside of work, Joe is either cooking, bodybuilding, or watching YouTube videos about non-duality.",
        twitter: "https://twitter.com/corepresentable",
        linkedin: "https://www.linkedin.com/in/joseph-hirsh/",
    },
]


